### ISSUE TITLE
Displaying respective tags on the page itself

### ISSUE THREAD

**Issue by thebrokencoder** [PontusHorn/Pico-Tags#10]
I am trying to display the respective tags of the page on the page using the `.md` file.

`<p class="article_date">%meta.date_formatted%<br>%page.meta.tags%</p>`

The date is appearing however instead of the tag, the whole string `'%mata.page.tags%'` appears,

`December 20, 2019`
`%page.meta.tags%`

I tried `%meta.page.tags%` with the same result. How do I display the tags associated with the page using the `.md` file?

**Comment by PontusHorn** [comment]
Have you tried using `%meta.tags%` instead?

**Comment by thebrokencoder** [comment]
I now did, and it didn't work. Every other meta, except tag(s) work.

**Comment by PontusHorn** [comment]
I see. Looked into it a bit, and it's because the tags meta header is converted into an array in the plugin, and Pico doesn't support using array variables in the page content.

What you can do is use them in a template file, which may be more along the lines of what you're trying to do anyway:

```twig
Tags: {{ meta.tags|join(', ') }}
```

Does that work for your use case?

**Comment by thebrokencoder** [comment]
Yes, that worked. The reason why I didn't want to use the template to display the date/tags is because I didn't want to maintain another template just for blogs. Apparently, seems that's the only way now. :smile:

I also want to make the tags displayed on the post though template clickable, each leading to respective tag home page. This is how I am currently displaying the tags through the template:

```
<p class="article_date">Tags: {{ meta.tags|join(', ') }}<br>{{ meta.date_formatted }}<br>--</p>
```

Houston, we have another problem! When you add more than one tag separated by comma in the .md file, the website parses it as one single tag instead of multiple tags separated by a comma.

Eg, An article with `Tags: Support, Docs` is given the tag `Support, Docs` instead of `Support` and `Docs`.

This is the code for listing the posts and tags associated,
```
{% for page in pages|sort_by("time")|reverse %}
{% if (page.id starts with "blog/") and not (page.id starts with "blog/tags/") and not page.hidden %}
<div class="blog">
<h2><a href="{{ page.url }}">{{ page.title }}</a></h2>
<p><a href="{{ base_url }}/blog/tags/{{ page.meta.tags|lower }}">{{ page.meta.tags }}</a></p>
</div>
{% endif %}
{% endfor %}

```
The `<a>` tag is applied on the complete list of tags, which is why the whole comma separated strings is considered as one tag. How do I separate them?

**Comment by PontusHorn** [comment]
The plugin doesn't make the parsed tag array available there, but you can approximate the same thing in Twig:

```twig
{% if page.meta.tags %}
  <p>
    {% for tag in page.meta.tags|split(',') %}
      <a href="{{ base_url }}/blog/tags/{{ tag|lower|trim }}">{{ tag|trim }}</a>{% if not loop.last %}, {% endif %}
    {% endfor %}
  </p>
{% endif %}
```

As for maintaining a separate template just for blogs, that's understandable, but if you use template extension it can be pretty tidy and maintainable. Here's the docs for that if you're curious and don't already know about it: https://twig.symfony.com/doc/3.x/tags/extends.html

**Comment by PontusHorn** [comment]
Did you manage to accomplish what you wanted?

**Comment by thebrokencoder** [comment]
Oh yes, it didn't work! I left for a trip thinking I had replied after you posted. I just returned and apparently I hadn't replied to your post. I didn't have access to anything much except email when I got your reply. Apologies, and many thanks for following up on this.

That code to separate the tags did work. Thanks. Anyway, for now, I have moved to maintain two separate templates for the blog post list and blog post. As you mentioned, extensions seems to be a better idea and I'll have to go through it before seeing how I can implement it.

Thanks again by the way.

**Comment by thebrokencoder** [comment]
Hey @PontusHorn, extremely sorry about  my previous comment confirming that the tags were clickable. I've been confused and careless and I should apologize first for being so. I mistook the issue for the original issue - not displaying tags on page - and judged the code to be working since I saw that the tags were displayed on the page, which was in fact because of the code mentioned in an [earlier comment](https://github.com/PontusHorn/Pico-Tags/issues/10#issuecomment-571714276).

Coming back to the issue of tags being clickable, the code on [this comment](https://github.com/PontusHorn/Pico-Tags/issues/10#issuecomment-571736967) just leaves an empty line on the page - an empty `p` tag confirmed by checking the source (ctrl+u). Also, I have changed the `page.meta.tags` to `meta.tags` in the code only to see the same result.

I also have used extensions, and it's easier to manage now.  Thanks for that.

**Comment by PontusHorn** [comment]
Hey! Sorry I dropped the ball on this. Are you still having issues with it?

**Comment by thebrokencoder** [comment]
Hey @PontusHorn, that's alright, don't be sorry.

Yes, I still have the first issue raised [here](https://github.com/PontusHorn/Pico-Tags/issues/10#issuecomment-571714276): making the tags clickable on the post page. The tags are being displayed on the blog post twig with this code:

`<p>{{ meta.tags|join(', ') }}</p>`

With the help of your [code](https://github.com/PontusHorn/Pico-Tags/issues/10#issuecomment-571736967),  I modified it to be clickable:

`<p><a href="{{ base_url }}/blog/tags/{{ meta.tags|join(', ')|lower }}">{{ meta.tags|join(', ') }}</a></p>`

But this modification works fine only with single tags. If there are multiple tags, it is treated as one single tag post (like it appeared on the blog list page which you helped me resolved). I tried the below variation as well, to no avail.
```
{% for tag in page.meta.tags|split(',') %}
<a href="{{ base_url }}/blog/tags/{{ meta.tags|join(', ')|lower }}">{{ meta.tags|join(', ') }}</a>{% if not loop.last %}, {% endif %}
{% endfor %}
```
I need to sort this code out to make individual tags clickable.

**Comment by PontusHorn** [comment]
Right, I think I got `meta.tags` and `page.meta.tags` confused in my example...

I was able to get it working in my test environment using this:
```twig
{% for tag in meta.tags %}
    <a href="{{ base_url }}/blog/tags/{{ tag|lower|trim }}">{{ tag|trim }}</a>{% if not loop.last %},{% endif %}
{% endfor %}
```

Note that we're using the `tag` variable to refer to each singular tag. The variable is defined by looping over `meta.tags`, which is a list.

Let me know if that works!

**Comment by thebrokencoder** [comment]
Oh no @PontusHorn, I don't think you were confused. The [example you gave](https://github.com/PontusHorn/Pico-Tags/issues/10#issuecomment-571736967) was for the blog list page and it works fine, whereas I was trying to work the same thing out in the post page too. The above code works perfectly for the post page too.

Many thanks to you. To be safer, I am leaving this Issue open for a day just to make sure I haven't messed up or misunderstood anything like last time. I shall close it then. Thanks again.

**Comment by PontusHorn** [comment]
No worries, glad it worked out!

**Comment by Discostu36** [comment]
Adding this to my blog post template works fine:
`<p>{{ meta.tags|join(', ') }}</p>`

This on the other hand leads to a blank page 
`{% for tag in meta.tags %}
    <a href="{{ base_url }}/tags/{{ tag|lower|trim }}">{{ tag|trim }}</a>{% if not loop.last %},{% endif %}
{% endfor %}`

What could be the cause of this?

**Comment by PontusHorn** [comment]
Hey @Discostu36. The code I had above works for me, but when I copy paste your code above I seem to get some invisible characters around a lot of the words, which does seem to cause the page to crash. If I just type it out as it looks, it works fine. Can you try that?

**Comment by Discostu36** [comment]
Thank you, this seems to have been some weird encoding error on my end. Maybe trying to edit code on a smartphone isn't the best idea.
