### ISSUE TITLE
PHP fatal error: unknown "get_all_tags" function

### ISSUE THREAD

**Issue by spiffin** [PontusHorn/Pico-Tags#11]
Using the latest Pico (v2.1.1) fresh install & latest version of the plugin as of April 2020 and following instructions in the README, specifically: "In themes/default/tags.html" - the 4th line: "{% set tags = get_all_tags() %}" gives a PHP fatal error: 
`[10-Apr-2020] PHP Fatal error:  Uncaught Twig_Error_Syntax: Unknown "get_all_tags" function. in /themes/mytheme/tags.html:4
Stack trace:
#0 /vendor/twig/twig/lib/Twig/ExpressionParser.php(377): Twig_ExpressionParser->getFunctionNodeClass('get_all_tags', 4)
#1 /vendor/twig/twig/lib/Twig/ExpressionParser.php(162): Twig_ExpressionParser->getFunctionNode('get_all_tags', 4)
#2 /vendor/twig/twig/lib/Twig/ExpressionParser.php(102): Twig_ExpressionParser->parsePrimaryExpression()
#3 /vendor/twig/twig/lib/Twig/ExpressionParser.php(55): Twig_ExpressionParser->getPrimary()
#4 /vendor/twig/twig/lib/Twig/ExpressionParser.php(587): Twig_ExpressionParser->parseExpression()
#5 /vendor/twig/twig/lib/Twig/TokenParser/Set.php(41): Twig_ExpressionParser->parseMultitargetExpression()
#6 /vendor/twig/twig/lib/Twig/Parser.php(192): Twig_TokenParser_Set->parse(Object( in /themes/mytheme/tags.html on line 4`

**Comment by PontusHorn** [comment]
Hey! That's a shame. I'm not able to replicate this. What version of PHP are you using? Can you paste your `composer.lock`?

**Comment by spiffin** [comment]
Hi. Thanks for getting back to me. I'm running PHP 7.3.14 (FPM/FastCGI) with the necessary modules. I don't use composer so my composer.lock is untouched: copy attached.
[composer.lock.zip](https://github.com/PontusHorn/Pico-Tags/files/4462130/composer.lock.zip)

**Comment by PontusHorn** [comment]
Hi! Sorry for taking so long. Are you still encountering this? I've tried again with various configurations and can't manage to replicate your issue. The only reason I can think of is for that error to appear is it the plugin wasn't up-to-date, but you said it was, so I'm at a loss.
