### ISSUE TITLE
Returns empty tags array when yaml array/collections (not comma separated string) passed as `Tags`

### ISSUE THREAD

**Issue by adnan360** [PontusHorn/Pico-Tags#12]
I was using content from a Hexo project. Hexo uses yaml arrays or sequence as tags.

That means:
```
tags:
 - tag1
 - tag2
```

As opposed to:
```
tags: tag1, tag2
```

which is suggested in the readme. I have hundreds of posts, changing in which is a cumbersome task. So having the plugin support sequence would be nice. Having  sequence as value in yaml causes the `parseTags` function to return empty array. Probably this part is to blame:

```
    private static function parseTags($tags)
    {
        if (!is_string($tags) || mb_strlen($tags) <= 0) {
            return array();
        }
...
```

As a preliminary test I changed to `return $tags;` and it was working as it should.

**Comment by PontusHorn** [comment]
Thanks for the contribution!
