### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by epigraphe** [PontusHorn/Pico-Tags#2]
Good afternoon.
Thanks to you, I solved the problem with the incorrect version of php, but now there is a question about functionality.

In the content folder I created a file index.md and folder named blog. In the "blog" directory i have 3 files with names blog1, blog2, blog3 in which is written

```
---
 Title: My first blog post
 Date: 2015-09-16 13:37:00
 Tags: foo, bar, blog
 ---

 
 My first blog post 
```
(second and third in blog2 and blog3)

and an index.md file with

```
 ---
Title: Blog
Filter: blog
---
Something
```

When i try to open http://localhost/blog/ browser opens the page, but shows only the text in file.

**Comment by PontusHorn** [comment]
My documentation skills might leave something to be desired. :)

Your index.md page needs to use a template (specified with the `Template:` tag in the header) that loops through the pages and prints them out in a way that you desire.

Let's say your index.md looks like this:

```
---
Title: Blog
Filter: blog
Template: blog-list
---
Something
```

Then you would need a template file, e.g. **themes/default/blog-list.html**, containing something like this in the content section:
```twig
{{ content }}
{% for page in pages if page.title %}
    <article>
        <h2><a href="{{ page.url }}">{{ page.title }}</a></h2>
        <p>{{ page.description }}</p>
    </article>
{% endfor %}
```

The `{{ content }}` includes the contents of the page you're viewing, and the rest lists out the pages filtered out by the `Filter:` tag.

Hope that's clear enough. Let me know if you have any other questions.
