### ISSUE TITLE
Compability with current Pico version

### ISSUE THREAD

**Issue by sookoll** [PontusHorn/Pico-Tags#6]
Filter seems to not work in current Pico version. Tags still work.

**Comment by PontusHorn** [comment]
Hi! Could you describe the issue in a bit more detail, e.g. by including steps to reproduce, expected behaviour, and actual behaviour?

**Comment by sookoll** [comment]
In one page:
```
---
Title: Page one
Tags: foo
---
```
In template `{{ meta.tags|join(', ') }}` work.

In second page:
```
---
Title: Page two
Filter: foo
---
```
In template `{% for page in pages %}` will loop over all pages, not just pages with tag: foo.

**Comment by PontusHorn** [comment]
I just tried this with a fresh install and it seems to work. What Pico version are you using?

**Comment by sookoll** [comment]
2.0.4

**Comment by PontusHorn** [comment]
That's the version I tested without issue as well. Are you using any other plugins that might interfere? Alternatively, would it be possible for you to create a minimal reproduction of the issue based on a fresh install of Pico that I can look at?

**Comment by PontusHorn** [comment]
Closing this for now. If you can create a minimal reproduction of the issue, feel free to open a new issue with that.
